### PR TITLE
Upgrade to IntelliJ 2020.3

### PR DESCRIPTION
**Pull request by sachin-surya-soft**

### CODE REVIEW

**Review by gps — CHANGES_REQUESTED** [review]
@sachin-surya-soft are you sure we still need to install the Kotlin plugin manually? @chetanfaris says it's not needed for IntelliJ IDEA.

Further, are there any updates to the Android tools as well?

**Comment by sachin-surya-soft** [comment]
> @sachin-surya-soft are you sure we still need to install the Kotlin plugin manually? @chetanfaris says it's not needed for IntelliJ IDEA.

I will double check this.

> Further, are there any updates to the Android tools as well?

I will check that.

**Comment by sachin-surya-soft** [comment]
> > @sachin-surya-soft are you sure we still need to install the Kotlin plugin manually? @chetanfaris says it's not needed for IntelliJ IDEA.


Yes, latest version of Intellij includes Kotlin plugin. Updated the PR, to remove the manual update.

**Comment by sachin-surya-soft** [comment]
> Further, are there any updates to the Android tools as well?

Yes, there was an update for Android command Lines Tools, I have updated that also.

**Review by gps — APPROVED** [review]
Thanks @sachin-surya-soft!

**Pull request merged**
